### ISSUE TITLE
Installation Error: Cannot install using npm

### ISSUE THREAD

**Issue by tom-avilius** [JaroslawPokropinski/SetWindowPos#2]
### Bug Description
During install the following is logged to the screen and the module is not installed.

npm i win-setwindowpos

> win-setwindowpos@2.1.0 install D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos
> node-gyp rebuild

D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos>if not defined npm_config_node_gyp (node "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
(node:77656) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
Traceback (most recent call last):
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 554, in script_main
    return main(sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 547, in main
    return gyp_main(args)
           ^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 520, in gyp_main
    [generator, flat_list, targets, data] = Load(
                                            ^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 136, in Load
    result = gyp.input.Load(build_files, default_variables, includes[:],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2782, in Load
    LoadTargetBuildFile(build_file, data, aux_data,
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 391, in LoadTargetBuildFile
    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 234, in LoadOneBuildFile
    build_file_contents = open(build_file_path, 'rU').read()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rU' while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\aaars\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aaars\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Aaarsh\javascript\splash\node_modules\win-setwindowpos
gyp ERR! node -v v18.14.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm WARN splash@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@3.1.0 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@3.3.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@3.3.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! win-setwindowpos@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the win-setwindowpos@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaars\AppData\Roaming\npm-cache\_logs\2023-03-03T13_54_52_827Z-debug.log

### To Reproduce
- Initialize an empty repository using `npm init`
- (maybe optional) run `npm install electron`
- run `npm install win-setwindowpos`

### Expected behaviour
win-setwindowpos should be installed.

### Version Info
node => v18.14.0
npm => v6.14.18
node-gyp => v9.3.1
electron => v23.1.1
electron-squirrel-startup => v1.0.0
windows 10 => build 19045
visual studio => 2017
python => v3.11

**Comment by JaroslawPokropinski** [comment]
Hi, I am not sure what is the issue here but I don't think python 3.11 is supported by node-gyp.
For me build passes without issues on Windows 11, python 3.9, npm 9.3.1.

Can you try downgrading python?

**Comment by tom-avilius** [comment]
Greetings. The problem was with python. As it happens python 2.7 worked for me in windows 10. I am grateful for your help and for the module.

**Comment by tom-avilius** [comment]
There is one more thing I wish to ask that is not regarding any issue. I do not want the Z order of my window to change. I tried the following code: 
```javascript
SetWindowPos(
    mainWindow.getNativeWindowHandle(),
    HWND_BOTTOM,
    0,
    700,
    800,
    600,
    SWP_NOZORDER,
    );
```
